### ISSUE TITLE
Problem with  DenseNet_predict.py

### ISSUE THREAD

**Issue by Ramalheira07** [UCSD-AI4H/COVID-CT#29]
FileNotFoundError: [Errno 2] No such file or directory: 'new_data/newtxt/train.txt'.

In Folder new_data and old_data/oldtxt/trainCT_NonCOVID.txt. 
Is miss Train, val.txt and Test files.

**Comment by jkooy** [comment]
They are in the `Data-split` repo. You need to change your path.

**Comment by Ramalheira07** [comment]
But Train, val.txt and Test files ????

Dont Exist in Data-Split folder.

**Comment by jkooy** [comment]
You can just put the new image you want to predict in the image folder and add the image name to the test txt file.

**Comment by SadafNaz1980** [comment]
I somehow managed to give paths for text files. However, still struggling to give a proper path for images processed. How and where to give a path for all the images? 

I'm receiving this error: [Errno 2] No such file or directory

https://github.com/UCSD-AI4H/COVID-CT/blob/master/baseline%20methods/DenseNet169/DenseNet_predict.py 
On line 155, what will be the root directory path? 
What I'm doing:
I downloaded the master file which has all text and image folders and files. 
Instead of 
root_dir='new_data/4.4_image' 
I'm trying
root_dir="C:\\Users\\sadaf\\Desktop\\Dynamic Fusion - CT data\\COVID-CT-master\\Images-processed\\",

Not working in my case. Any help will be appreciated. Thank you
